INSERT INTO m_workers VALUES
(1, 'comB-worker-1', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'comB-worker-2', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'comB-worker-3', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
