INSERT INTO m_workers VALUES
(1, 'comA-worker-1', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'comA-worker-2', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'comA-worker-3', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
