INSERT INTO books VALUES
(1, 'name-1', 'isbn-1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'name-2', 'isbn-2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'name-3', 'isbn-3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'name-4', 'isbn-4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'name-5', 'isbn-5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'name-6', 'isbn-6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
